package com.superkeyword;

class Parentt {

}
public class Child extends Parentt{

    Child()
    { //super(); //generated by compiler
        System.out.println("Child 0-arg constructor");
    }
    public static void main(String[] args)
        {
            new Child();
        }

}

